"use client";

import { useEffect } from "react";

// ---------------------------------------------------------------------------
// ShareParamCleanup — strips the `?via=` share-attribution param from the
// address bar after hydration (mounted once in the root layout).
//
// Share links generated by ShareTargets carry `?via={network}` so GA4 can
// attribute inbound share traffic (the GA page_view fires with the full URL
// before this effect runs). Once captured, the param is dead weight: leaving
// it in the address bar means anyone re-copying the URL propagates a stale
// source label, polluting attribution — the YouTube `?si=` lesson. A silent
// history.replaceState keeps the canonical clean without a navigation.
//
// Deliberately does NOT touch utm_* params — external campaigns own those.
// ---------------------------------------------------------------------------

export function ShareParamCleanup() {
  useEffect(() => {
    const url = new URL(window.location.href);
    if (!url.searchParams.has("via")) return;
    url.searchParams.delete("via");
    window.history.replaceState(window.history.state, "", url.toString());
  }, []);

  return null;
}
