// Generated by Supabase MCP `generate_typescript_types`. Re-run after schema changes.
// Source of truth: supabase/migrations/*.sql.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      card_ai_calls: {
        Row: {
          action: string;
          created_at: string;
          id: string;
          user_id: string;
        };
        Insert: {
          action: string;
          created_at?: string;
          id?: string;
          user_id: string;
        };
        Update: {
          action?: string;
          created_at?: string;
          id?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      credit_ledger: {
        Row: {
          balance_after: number;
          created_at: string;
          delta: number;
          id: string;
          reason: string;
          idempotency_key: string | null;
          user_id: string;
        };
        Insert: {
          balance_after: number;
          created_at?: string;
          delta: number;
          id?: string;
          reason: string;
          idempotency_key?: string | null;
          user_id: string;
        };
        Update: {
          balance_after?: number;
          created_at?: string;
          delta?: number;
          id?: string;
          reason?: string;
          idempotency_key?: string | null;
          user_id?: string;
        };
        Relationships: [];
      };
      stripe_events: {
        Row: {
          id: string;
          processed_at: string;
          type: string;
        };
        Insert: {
          id: string;
          processed_at?: string;
          type: string;
        };
        Update: {
          id?: string;
          processed_at?: string;
          type?: string;
        };
        Relationships: [];
      };
      comment_reports: {
        Row: {
          comment_id: string;
          created_at: string;
          details: string | null;
          id: string;
          reason: string;
          reporter_id: string;
          resolved_at: string | null;
          resolved_by: string | null;
          status: string;
        };
        Insert: {
          comment_id: string;
          created_at?: string;
          details?: string | null;
          id?: string;
          reason: string;
          reporter_id: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          status?: string;
        };
        Update: {
          comment_id?: string;
          created_at?: string;
          details?: string | null;
          id?: string;
          reason?: string;
          reporter_id?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "comment_reports_comment_id_fkey";
            columns: ["comment_id"];
            isOneToOne: false;
            referencedRelation: "card_comments";
            referencedColumns: ["id"];
          },
        ];
      };
      card_reports: {
        Row: {
          card_id: string;
          created_at: string;
          details: string | null;
          id: string;
          reason: string;
          reporter_id: string;
          resolved_at: string | null;
          resolved_by: string | null;
          status: string;
        };
        Insert: {
          card_id: string;
          created_at?: string;
          details?: string | null;
          id?: string;
          reason: string;
          reporter_id: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          status?: string;
        };
        Update: {
          card_id?: string;
          created_at?: string;
          details?: string | null;
          id?: string;
          reason?: string;
          reporter_id?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "card_reports_card_id_fkey";
            columns: ["card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
        ];
      };
      card_comments: {
        Row: {
          author_id: string;
          body: string;
          card_id: string;
          created_at: string;
          id: string;
          updated_at: string;
        };
        Insert: {
          author_id: string;
          body: string;
          card_id: string;
          created_at?: string;
          id?: string;
          updated_at?: string;
        };
        Update: {
          author_id?: string;
          body?: string;
          card_id?: string;
          created_at?: string;
          id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "card_comments_card_id_fkey";
            columns: ["card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
        ];
      };
      card_exports: {
        Row: {
          card_id: string;
          created_at: string;
          file_url: string;
          format: string;
          height: number;
          id: string;
          owner_id: string;
          storage_path: string;
          width: number;
        };
        Insert: {
          card_id: string;
          created_at?: string;
          file_url: string;
          format: string;
          height: number;
          id?: string;
          owner_id: string;
          storage_path: string;
          width: number;
        };
        Update: {
          card_id?: string;
          created_at?: string;
          file_url?: string;
          format?: string;
          height?: number;
          id?: string;
          owner_id?: string;
          storage_path?: string;
          width?: number;
        };
        Relationships: [
          {
            foreignKeyName: "card_exports_card_id_fkey";
            columns: ["card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
        ];
      };
      follows: {
        Row: {
          created_at: string;
          follower_id: string;
          following_id: string;
        };
        Insert: {
          created_at?: string;
          follower_id: string;
          following_id: string;
        };
        Update: {
          created_at?: string;
          follower_id?: string;
          following_id?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          actor_id: string | null;
          card_id: string | null;
          comment_id: string | null;
          created_at: string;
          id: string;
          read_at: string | null;
          recipient_id: string;
          type: string;
        };
        Insert: {
          actor_id?: string | null;
          card_id?: string | null;
          comment_id?: string | null;
          created_at?: string;
          id?: string;
          read_at?: string | null;
          recipient_id: string;
          type: string;
        };
        Update: {
          actor_id?: string | null;
          card_id?: string | null;
          comment_id?: string | null;
          created_at?: string;
          id?: string;
          read_at?: string | null;
          recipient_id?: string;
          type?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_card_id_fkey";
            columns: ["card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
        ];
      };
      card_likes: {
        Row: {
          card_id: string;
          created_at: string;
          id: string;
          user_id: string;
        };
        Insert: {
          card_id: string;
          created_at?: string;
          id?: string;
          user_id: string;
        };
        Update: {
          card_id?: string;
          created_at?: string;
          id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "card_likes_card_id_fkey";
            columns: ["card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
        ];
      };
      card_set_items: {
        Row: {
          card_id: string;
          created_at: string;
          id: string;
          position: number;
          set_id: string;
        };
        Insert: {
          card_id: string;
          created_at?: string;
          id?: string;
          position?: number;
          set_id: string;
        };
        Update: {
          card_id?: string;
          created_at?: string;
          id?: string;
          position?: number;
          set_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "card_set_items_card_id_fkey";
            columns: ["card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "card_set_items_set_id_fkey";
            columns: ["set_id"];
            isOneToOne: false;
            referencedRelation: "card_sets";
            referencedColumns: ["id"];
          },
        ];
      };
      card_sets: {
        Row: {
          cover_url: string | null;
          created_at: string;
          description: string | null;
          icon_code: string | null;
          icon_url: string | null;
          id: string;
          owner_id: string;
          slug: string;
          title: string;
          updated_at: string;
          visibility: string;
        };
        Insert: {
          cover_url?: string | null;
          created_at?: string;
          description?: string | null;
          icon_code?: string | null;
          icon_url?: string | null;
          id?: string;
          owner_id: string;
          slug: string;
          title: string;
          updated_at?: string;
          visibility?: string;
        };
        Update: {
          cover_url?: string | null;
          created_at?: string;
          description?: string | null;
          icon_code?: string | null;
          icon_url?: string | null;
          id?: string;
          owner_id?: string;
          slug?: string;
          title?: string;
          updated_at?: string;
          visibility?: string;
        };
        Relationships: [];
      };
      card_templates: {
        Row: {
          config: Json;
          created_at: string;
          description: string | null;
          game_system_id: string;
          id: string;
          is_active: boolean;
          key: string;
          name: string;
        };
        Insert: {
          config?: Json;
          created_at?: string;
          description?: string | null;
          game_system_id: string;
          id?: string;
          is_active?: boolean;
          key: string;
          name: string;
        };
        Update: {
          config?: Json;
          created_at?: string;
          description?: string | null;
          game_system_id?: string;
          id?: string;
          is_active?: boolean;
          key?: string;
          name?: string;
        };
        Relationships: [
          {
            foreignKeyName: "card_templates_game_system_id_fkey";
            columns: ["game_system_id"];
            isOneToOne: false;
            referencedRelation: "game_systems";
            referencedColumns: ["id"];
          },
        ];
      };
      cards: {
        Row: {
          art_position: Json;
          art_url: string | null;
          artist_credit: string | null;
          back_face: Json | null;
          card_type: string | null;
          color_identity: string[];
          cost: string | null;
          created_at: string;
          defense: string | null;
          flavor_text: string | null;
          frame_style: Json;
          game_system_id: string;
          id: string;
          layout: string;
          loyalty: string | null;
          mana_value: number | null;
          metadata: Json;
          oracle_text: string | null;
          owner_id: string;
          layout_version: number | null;
          back_card_id: string | null;
          parent_card_id: string | null;
          power: string | null;
          primary_set_id: string | null;
          rarity: string | null;
          rendered_at: string | null;
          rendered_image_url: string | null;
          rules_text: string | null;
          set_icon_code: string | null;
          set_icon_url: string | null;
          slug: string;
          source_scryfall_id: string | null;
          subtypes: string[];
          tags: string[];
          supertype: string | null;
          template_id: string | null;
          title: string;
          toughness: string | null;
          updated_at: string;
          likes_count: number;
          view_count: number;
          color_count: number | null;
          visibility: string;
        };
        Insert: {
          art_position?: Json;
          art_url?: string | null;
          artist_credit?: string | null;
          back_face?: Json | null;
          card_type?: string | null;
          color_identity?: string[];
          cost?: string | null;
          created_at?: string;
          defense?: string | null;
          flavor_text?: string | null;
          frame_style?: Json;
          game_system_id: string;
          id?: string;
          layout?: string;
          loyalty?: string | null;
          mana_value?: number | null;
          metadata?: Json;
          oracle_text?: string | null;
          owner_id: string;
          back_card_id?: string | null;
          parent_card_id?: string | null;
          power?: string | null;
          primary_set_id?: string | null;
          rarity?: string | null;
          layout_version?: number | null;
          rendered_at?: string | null;
          rendered_image_url?: string | null;
          rules_text?: string | null;
          set_icon_code?: string | null;
          set_icon_url?: string | null;
          slug: string;
          source_scryfall_id?: string | null;
          subtypes?: string[];
          tags?: string[];
          supertype?: string | null;
          template_id?: string | null;
          title: string;
          toughness?: string | null;
          updated_at?: string;
          likes_count?: number;
          view_count?: number;
          visibility?: string;
        };
        Update: {
          art_position?: Json;
          art_url?: string | null;
          artist_credit?: string | null;
          back_face?: Json | null;
          card_type?: string | null;
          color_identity?: string[];
          cost?: string | null;
          created_at?: string;
          defense?: string | null;
          flavor_text?: string | null;
          frame_style?: Json;
          game_system_id?: string;
          id?: string;
          layout?: string;
          loyalty?: string | null;
          mana_value?: number | null;
          metadata?: Json;
          oracle_text?: string | null;
          owner_id?: string;
          back_card_id?: string | null;
          parent_card_id?: string | null;
          power?: string | null;
          primary_set_id?: string | null;
          rarity?: string | null;
          layout_version?: number | null;
          rendered_at?: string | null;
          rendered_image_url?: string | null;
          rules_text?: string | null;
          set_icon_code?: string | null;
          set_icon_url?: string | null;
          slug?: string;
          source_scryfall_id?: string | null;
          subtypes?: string[];
          tags?: string[];
          supertype?: string | null;
          template_id?: string | null;
          title?: string;
          toughness?: string | null;
          updated_at?: string;
          likes_count?: number;
          view_count?: number;
          visibility?: string;
        };
        Relationships: [
          {
            foreignKeyName: "cards_game_system_id_fkey";
            columns: ["game_system_id"];
            isOneToOne: false;
            referencedRelation: "game_systems";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "cards_parent_card_id_fkey";
            columns: ["parent_card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "cards_primary_set_id_fkey";
            columns: ["primary_set_id"];
            isOneToOne: false;
            referencedRelation: "card_sets";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "cards_template_id_fkey";
            columns: ["template_id"];
            isOneToOne: false;
            referencedRelation: "card_templates";
            referencedColumns: ["id"];
          },
        ];
      };
      game_systems: {
        Row: {
          created_at: string;
          description: string | null;
          id: string;
          is_active: boolean;
          key: string;
          name: string;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          id?: string;
          is_active?: boolean;
          key: string;
          name: string;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          id?: string;
          is_active?: boolean;
          key?: string;
          name?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          accent_color: string | null;
          avatar_url: string | null;
          banner_url: string | null;
          bio: string | null;
          bluesky_url: string | null;
          created_at: string;
          discord_url: string | null;
          display_name: string | null;
          github_url: string | null;
          id: string;
          instagram_url: string | null;
          pinned_card_ids: string[];
          tiktok_url: string | null;
          twitter_url: string | null;
          updated_at: string;
          username: string | null;
          website_url: string | null;
          youtube_url: string | null;
          stripe_customer_id: string | null;
          subscription_tier: string;
          subscription_status: string | null;
          stripe_subscription_id: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          credits: number;
          is_admin: boolean;
        };
        Insert: {
          accent_color?: string | null;
          avatar_url?: string | null;
          banner_url?: string | null;
          bio?: string | null;
          bluesky_url?: string | null;
          created_at?: string;
          discord_url?: string | null;
          display_name?: string | null;
          github_url?: string | null;
          id: string;
          instagram_url?: string | null;
          pinned_card_ids?: string[];
          tiktok_url?: string | null;
          twitter_url?: string | null;
          updated_at?: string;
          username?: string | null;
          website_url?: string | null;
          youtube_url?: string | null;
          stripe_customer_id?: string | null;
          subscription_tier?: string;
          subscription_status?: string | null;
          stripe_subscription_id?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          credits?: number;
          is_admin?: boolean;
        };
        Update: {
          accent_color?: string | null;
          avatar_url?: string | null;
          banner_url?: string | null;
          bio?: string | null;
          bluesky_url?: string | null;
          created_at?: string;
          discord_url?: string | null;
          display_name?: string | null;
          github_url?: string | null;
          id?: string;
          instagram_url?: string | null;
          pinned_card_ids?: string[];
          tiktok_url?: string | null;
          twitter_url?: string | null;
          updated_at?: string;
          username?: string | null;
          website_url?: string | null;
          youtube_url?: string | null;
          stripe_customer_id?: string | null;
          subscription_tier?: string;
          subscription_status?: string | null;
          stripe_subscription_id?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          credits?: number;
          is_admin?: boolean;
        };
        Relationships: [];
      };
      set_likes: {
        Row: {
          created_at: string;
          id: string;
          set_id: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          set_id: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          set_id?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      scryfall_calls: {
        Row: {
          action: string;
          created_at: string;
          id: string;
          user_id: string;
        };
        Insert: {
          action: string;
          created_at?: string;
          id?: string;
          user_id: string;
        };
        Update: {
          action?: string;
          created_at?: string;
          id?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      challenges: {
        Row: {
          created_at: string;
          description: string;
          ends_at: string;
          featured: boolean;
          hero_image_url: string | null;
          id: string;
          slug: string;
          starts_at: string;
          tag: string;
          title: string;
        };
        Insert: {
          created_at?: string;
          description: string;
          ends_at: string;
          featured?: boolean;
          hero_image_url?: string | null;
          id?: string;
          slug: string;
          starts_at?: string;
          tag: string;
          title: string;
        };
        Update: {
          created_at?: string;
          description?: string;
          ends_at?: string;
          featured?: boolean;
          hero_image_url?: string | null;
          id?: string;
          slug?: string;
          starts_at?: string;
          tag?: string;
          title?: string;
        };
        Relationships: [];
      };
      custom_pips: {
        Row: {
          created_at: string;
          id: string;
          image_url: string;
          owner_id: string;
          symbol: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          image_url: string;
          owner_id: string;
          symbol: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          image_url?: string;
          owner_id?: string;
          symbol?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      consume_credits: {
        Args: { p_amount: number; p_reason: string };
        Returns: {
          ok: boolean;
          balance: number;
        }[];
      };
      grant_credits: {
        Args: {
          p_user_id: string;
          p_amount: number;
          p_reason: string;
          p_idempotency_key?: string;
        };
        Returns: number;
      };
      credit_ledger_daily: {
        Args: { since: string };
        Returns: {
          day: string;
          spent: number;
        }[];
      };
      card_ai_calls_daily: {
        Args: { since: string };
        Returns: {
          count: number;
          day: string;
        }[];
      };
      scryfall_calls_daily: {
        Args: { since: string };
        Returns: {
          count: number;
          day: string;
        }[];
      };
      increment_card_view: {
        Args: { p_card_id: string };
        Returns: undefined;
      };
      card_like_rank: {
        Args: { p_card_id: string };
        Returns: number;
      };
      card_like_rank_in_set: {
        Args: { p_card_id: string; p_set_id: string };
        Returns: number;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;

// Convenience aliases used across the app.
export type Profile = Tables<"profiles">;
export type ProfileInsert = TablesInsert<"profiles">;
export type ProfileUpdate = TablesUpdate<"profiles">;

export type GameSystem = Tables<"game_systems">;
export type CardTemplate = Tables<"card_templates">;
export type Card = Tables<"cards">;
export type CardInsert = TablesInsert<"cards">;
export type CardUpdate = TablesUpdate<"cards">;

export type CardExport = Tables<"card_exports">;
export type CardExportInsert = TablesInsert<"card_exports">;

export type CardAiCall = Tables<"card_ai_calls">;
export type CardAiCallInsert = TablesInsert<"card_ai_calls">;

export type ScryfallCall = Tables<"scryfall_calls">;
export type ScryfallCallInsert = TablesInsert<"scryfall_calls">;

export type CardLike = Tables<"card_likes">;
export type CardLikeInsert = TablesInsert<"card_likes">;

export type CardSet = Tables<"card_sets">;
export type CardSetInsert = TablesInsert<"card_sets">;
export type CardSetUpdate = TablesUpdate<"card_sets">;

export type CardSetItem = Tables<"card_set_items">;
export type CardSetItemInsert = TablesInsert<"card_set_items">;

// Phase v2: comments on public cards.
export type CardComment = Tables<"card_comments">;
export type CardCommentInsert = TablesInsert<"card_comments">;
export type CardCommentUpdate = TablesUpdate<"card_comments">;

// Billing: subscription credits ledger + Stripe webhook dedupe.
export type CreditLedgerEntry = Tables<"credit_ledger">;
export type CreditLedgerInsert = TablesInsert<"credit_ledger">;
export type StripeEvent = Tables<"stripe_events">;

// Moderation: user-filed reports on public cards.
export type CardReport = Tables<"card_reports">;
export type CardReportInsert = TablesInsert<"card_reports">;
export type CommentReport = Tables<"comment_reports">;
export type CommentReportInsert = TablesInsert<"comment_reports">;

// In-app creator notifications (likes / comments / remixes / follows).
export type Notification = Tables<"notifications">;

// Creator follow graph.
export type Follow = Tables<"follows">;
