// Generated by Supabase MCP `generate_typescript_types`. Re-run after schema changes.
// Source of truth: supabase/migrations/*.sql.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      card_ai_calls: {
        Row: {
          action: string;
          created_at: string;
          id: string;
          user_id: string;
        };
        Insert: {
          action: string;
          created_at?: string;
          id?: string;
          user_id: string;
        };
        Update: {
          action?: string;
          created_at?: string;
          id?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      scryfall_calls: {
        Row: {
          action: string;
          created_at: string;
          id: string;
          user_id: string;
        };
        Insert: {
          action: string;
          created_at?: string;
          id?: string;
          user_id: string;
        };
        Update: {
          action?: string;
          created_at?: string;
          id?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      card_exports: {
        Row: {
          card_id: string;
          created_at: string;
          file_url: string;
          format: string;
          height: number;
          id: string;
          owner_id: string;
          storage_path: string;
          width: number;
        };
        Insert: {
          card_id: string;
          created_at?: string;
          file_url: string;
          format: string;
          height: number;
          id?: string;
          owner_id: string;
          storage_path: string;
          width: number;
        };
        Update: {
          card_id?: string;
          created_at?: string;
          file_url?: string;
          format?: string;
          height?: number;
          id?: string;
          owner_id?: string;
          storage_path?: string;
          width?: number;
        };
        Relationships: [
          {
            foreignKeyName: "card_exports_card_id_fkey";
            columns: ["card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
        ];
      };
      card_likes: {
        Row: {
          card_id: string;
          created_at: string;
          id: string;
          user_id: string;
        };
        Insert: {
          card_id: string;
          created_at?: string;
          id?: string;
          user_id: string;
        };
        Update: {
          card_id?: string;
          created_at?: string;
          id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "card_likes_card_id_fkey";
            columns: ["card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
        ];
      };
      card_set_items: {
        Row: {
          card_id: string;
          created_at: string;
          id: string;
          position: number;
          set_id: string;
        };
        Insert: {
          card_id: string;
          created_at?: string;
          id?: string;
          position?: number;
          set_id: string;
        };
        Update: {
          card_id?: string;
          created_at?: string;
          id?: string;
          position?: number;
          set_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "card_set_items_card_id_fkey";
            columns: ["card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "card_set_items_set_id_fkey";
            columns: ["set_id"];
            isOneToOne: false;
            referencedRelation: "card_sets";
            referencedColumns: ["id"];
          },
        ];
      };
      card_sets: {
        Row: {
          cover_url: string | null;
          created_at: string;
          description: string | null;
          id: string;
          owner_id: string;
          slug: string;
          title: string;
          updated_at: string;
          visibility: string;
        };
        Insert: {
          cover_url?: string | null;
          created_at?: string;
          description?: string | null;
          id?: string;
          owner_id: string;
          slug: string;
          title: string;
          updated_at?: string;
          visibility?: string;
        };
        Update: {
          cover_url?: string | null;
          created_at?: string;
          description?: string | null;
          id?: string;
          owner_id?: string;
          slug?: string;
          title?: string;
          updated_at?: string;
          visibility?: string;
        };
        Relationships: [];
      };
      card_templates: {
        Row: {
          config: Json;
          created_at: string;
          description: string | null;
          game_system_id: string;
          id: string;
          is_active: boolean;
          key: string;
          name: string;
        };
        Insert: {
          config?: Json;
          created_at?: string;
          description?: string | null;
          game_system_id: string;
          id?: string;
          is_active?: boolean;
          key: string;
          name: string;
        };
        Update: {
          config?: Json;
          created_at?: string;
          description?: string | null;
          game_system_id?: string;
          id?: string;
          is_active?: boolean;
          key?: string;
          name?: string;
        };
        Relationships: [
          {
            foreignKeyName: "card_templates_game_system_id_fkey";
            columns: ["game_system_id"];
            isOneToOne: false;
            referencedRelation: "game_systems";
            referencedColumns: ["id"];
          },
        ];
      };
      cards: {
        Row: {
          art_position: Json;
          art_url: string | null;
          artist_credit: string | null;
          back_face: Json | null;
          card_type: string | null;
          color_identity: string[];
          cost: string | null;
          created_at: string;
          defense: string | null;
          flavor_text: string | null;
          frame_style: Json;
          game_system_id: string;
          id: string;
          loyalty: string | null;
          metadata: Json;
          owner_id: string;
          parent_card_id: string | null;
          power: string | null;
          rarity: string | null;
          rules_text: string | null;
          slug: string;
          source_scryfall_id: string | null;
          subtypes: string[];
          supertype: string | null;
          template_id: string | null;
          title: string;
          toughness: string | null;
          updated_at: string;
          visibility: string;
        };
        Insert: {
          art_position?: Json;
          art_url?: string | null;
          artist_credit?: string | null;
          back_face?: Json | null;
          card_type?: string | null;
          color_identity?: string[];
          cost?: string | null;
          created_at?: string;
          defense?: string | null;
          flavor_text?: string | null;
          frame_style?: Json;
          game_system_id: string;
          id?: string;
          loyalty?: string | null;
          metadata?: Json;
          owner_id: string;
          parent_card_id?: string | null;
          power?: string | null;
          rarity?: string | null;
          rules_text?: string | null;
          slug: string;
          source_scryfall_id?: string | null;
          subtypes?: string[];
          supertype?: string | null;
          template_id?: string | null;
          title: string;
          toughness?: string | null;
          updated_at?: string;
          visibility?: string;
        };
        Update: {
          art_position?: Json;
          art_url?: string | null;
          artist_credit?: string | null;
          back_face?: Json | null;
          card_type?: string | null;
          color_identity?: string[];
          cost?: string | null;
          created_at?: string;
          defense?: string | null;
          flavor_text?: string | null;
          frame_style?: Json;
          game_system_id?: string;
          id?: string;
          loyalty?: string | null;
          metadata?: Json;
          owner_id?: string;
          parent_card_id?: string | null;
          power?: string | null;
          rarity?: string | null;
          rules_text?: string | null;
          slug?: string;
          source_scryfall_id?: string | null;
          subtypes?: string[];
          supertype?: string | null;
          template_id?: string | null;
          title?: string;
          toughness?: string | null;
          updated_at?: string;
          visibility?: string;
        };
        Relationships: [
          {
            foreignKeyName: "cards_game_system_id_fkey";
            columns: ["game_system_id"];
            isOneToOne: false;
            referencedRelation: "game_systems";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "cards_parent_card_id_fkey";
            columns: ["parent_card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "cards_template_id_fkey";
            columns: ["template_id"];
            isOneToOne: false;
            referencedRelation: "card_templates";
            referencedColumns: ["id"];
          },
        ];
      };
      game_systems: {
        Row: {
          created_at: string;
          description: string | null;
          id: string;
          is_active: boolean;
          key: string;
          name: string;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          id?: string;
          is_active?: boolean;
          key: string;
          name: string;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          id?: string;
          is_active?: boolean;
          key?: string;
          name?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          bio: string | null;
          created_at: string;
          display_name: string | null;
          id: string;
          updated_at: string;
          username: string | null;
          website_url: string | null;
        };
        Insert: {
          avatar_url?: string | null;
          bio?: string | null;
          created_at?: string;
          display_name?: string | null;
          id: string;
          updated_at?: string;
          username?: string | null;
          website_url?: string | null;
        };
        Update: {
          avatar_url?: string | null;
          bio?: string | null;
          created_at?: string;
          display_name?: string | null;
          id?: string;
          updated_at?: string;
          username?: string | null;
          website_url?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      card_ai_calls_daily: {
        Args: { since: string };
        Returns: { day: string; count: number }[];
      };
      scryfall_calls_daily: {
        Args: { since: string };
        Returns: { day: string; count: number }[];
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;

// Convenience aliases used across the app.
export type Profile = Tables<"profiles">;
export type ProfileInsert = TablesInsert<"profiles">;
export type ProfileUpdate = TablesUpdate<"profiles">;

export type GameSystem = Tables<"game_systems">;
export type CardTemplate = Tables<"card_templates">;
export type Card = Tables<"cards">;
export type CardInsert = TablesInsert<"cards">;
export type CardUpdate = TablesUpdate<"cards">;

export type CardExport = Tables<"card_exports">;
export type CardExportInsert = TablesInsert<"card_exports">;

export type CardAiCall = Tables<"card_ai_calls">;
export type CardAiCallInsert = TablesInsert<"card_ai_calls">;

export type ScryfallCall = Tables<"scryfall_calls">;
export type ScryfallCallInsert = TablesInsert<"scryfall_calls">;

export type CardLike = Tables<"card_likes">;
export type CardLikeInsert = TablesInsert<"card_likes">;

export type CardSet = Tables<"card_sets">;
export type CardSetInsert = TablesInsert<"card_sets">;
export type CardSetUpdate = TablesUpdate<"card_sets">;

export type CardSetItem = Tables<"card_set_items">;
export type CardSetItemInsert = TablesInsert<"card_set_items">;
