import { cn } from "@/lib/utils";
import { DEFAULT_FRAME_TEMPLATE } from "@/types/card";
import type { ColorIdentity, FrameTemplate } from "@/types/card";

// ---------------------------------------------------------------------------
// FrameLayer — bottom-most z-index layer in CardPreview. Loads the chosen
// frame from public/frames/{template}/{colorKey}.{webp,png} (WebP variant
// preferred in the browser via a plain url(); the PNG is the master) and
// stretches it across the whole card. Sections (title, art, type, rules,
// footer) sit on top with their own translucent backgrounds.
//
// Color resolution rule:
//   - 0 colors → colorless "c"
//   - 1 color  → that color's key
//   - 2+       → multicolor "m"
//
// The PNGs are MSE-derived frames converted by scripts/convert-mse-frame.mjs
// and its siblings (build-era-frames / build-variation-frames); see the
// template notes in types/card.ts. Each template's geometry lives in
// lib/cards/template-layout.ts, and a (template, color) combo is only offered
// once verified in /admin/frame-compare — swapping a PNG is not a drop-in
// change.
// ---------------------------------------------------------------------------

const COLOR_KEY_LETTER: Record<ColorIdentity, string> = {
  white: "w",
  blue: "u",
  black: "b",
  red: "r",
  green: "g",
  colorless: "c",
  multicolor: "m",
};

/** Human word for a frame colour key — toast/error copy ("blue", "multicolor"). */
export const COLOR_KEY_WORDS: Record<string, string> = {
  w: "white",
  u: "blue",
  b: "black",
  r: "red",
  g: "green",
  c: "colorless",
  m: "multicolor",
};

export function colorWord(colorKey: string): string {
  return COLOR_KEY_WORDS[colorKey] ?? colorKey;
}

/** The single-select identity a frame colour key stands for (the inverse of
 *  pickFrameColorKey for one-colour identities; "m" → multicolor). */
export function colorIdentityForKey(colorKey: string): ColorIdentity {
  const found = (Object.entries(COLOR_KEY_LETTER) as [ColorIdentity, string][]).find(
    ([, letter]) => letter === colorKey,
  );
  return found?.[0] ?? "colorless";
}

export function pickFrameColorKey(
  colors: ColorIdentity[] | undefined,
): string {
  if (!colors || colors.length === 0) return "c";
  if (colors.length > 1) return "m";
  return COLOR_KEY_LETTER[colors[0]] ?? "c";
}

export function frameAssetPath(
  template: FrameTemplate,
  colorKey: string,
): string {
  return `/frames/${template}/${colorKey}.png`;
}

/** Sibling WebP variant of a /frames/**.png path (generated by
 *  scripts/generate-frame-webp.mjs — ~10× smaller, browser-only). */
export function webpVariant(pngPath: string): string {
  return pngPath.replace(/\.png$/, ".webp");
}

/** CSS background-image value for the small WebP variant. Plain url() on
 *  purpose: WebP decode has been universal since ~2020, while
 *  image-set(... type(...)) only landed ~2023 — and a browser too old for
 *  image-set would drop the whole declaration and render NO frame, so the
 *  "PNG fallback" inside image-set protects nobody. BROWSER ONLY — the
 *  server-side Satori bake never sees this: it reads the PNG bytes straight
 *  from disk (lib/render/card-frames.ts) and must stay on PNG. */
export function frameBackgroundImage(
  template: FrameTemplate,
  colorKey: string,
): string {
  return `url("${webpVariant(frameAssetPath(template, colorKey))}")`;
}

export function FrameLayer({
  template = DEFAULT_FRAME_TEMPLATE,
  colorIdentity,
  className,
  zIndex,
}: {
  template?: FrameTemplate;
  colorIdentity: ColorIdentity[] | undefined;
  className?: string;
  /** Optional inline z-index override. Templates that render a separate
   *  art layer beneath the frame (cut-out slot) pass a positive value so
   *  the frame sits on top of the art. Defaults to the base z-0 layer. */
  zIndex?: number;
}) {
  const colorKey = pickFrameColorKey(colorIdentity);
  return (
    <div
      aria-hidden
      className={cn(
        "pointer-events-none absolute inset-0",
        zIndex === undefined ? "z-0" : "",
        className,
      )}
      style={{
        backgroundImage: frameBackgroundImage(template, colorKey),
        backgroundSize: "100% 100%",
        backgroundRepeat: "no-repeat",
        ...(zIndex === undefined ? {} : { zIndex }),
      }}
    />
  );
}
