import { cn } from "@/lib/utils";
import { DEFAULT_FRAME_TEMPLATE } from "@/types/card";
import type { ColorIdentity, FrameTemplate } from "@/types/card";

// ---------------------------------------------------------------------------
// FrameLayer — bottom-most z-index layer in CardPreview. Loads the chosen
// frame from public/frames/{template}/{colorKey}.{webp,png} (WebP variant
// preferred in the browser via image-set(); the PNG is the master) and
// stretches it across the whole card. Sections (title, art, type, rules,
// footer) sit on top with their own translucent backgrounds.
//
// Color resolution rule (matches the existing pickGradient logic):
//   - 0 colors → colorless "c"
//   - 1 color  → that color's key
//   - 2+       → multicolor "m"
//
// The PNGs are clean original placeholders (see scripts/generate-frame-
// placeholders.ts). Drop your own PNGs at the same paths to upgrade the
// look — the file naming is the only contract.
// ---------------------------------------------------------------------------

const COLOR_KEY_LETTER: Record<ColorIdentity, string> = {
  white: "w",
  blue: "u",
  black: "b",
  red: "r",
  green: "g",
  colorless: "c",
  multicolor: "m",
};

export function pickFrameColorKey(
  colors: ColorIdentity[] | undefined,
): string {
  if (!colors || colors.length === 0) return "c";
  if (colors.length > 1) return "m";
  return COLOR_KEY_LETTER[colors[0]] ?? "c";
}

export function frameAssetPath(
  template: FrameTemplate,
  colorKey: string,
): string {
  return `/frames/${template}/${colorKey}.png`;
}

/** Sibling WebP variant of a /frames/**.png path (generated by
 *  scripts/generate-frame-webp.mjs — ~10× smaller, browser-only). */
export function webpVariant(pngPath: string): string {
  return pngPath.replace(/\.png$/, ".webp");
}

/** CSS background-image value that prefers the small WebP variant and falls
 *  back to the PNG master. BROWSER ONLY — the server-side Satori bake never
 *  sees this: it reads the PNG bytes straight from disk
 *  (lib/render/card-frames.ts) and must stay on PNG (Satori supports
 *  neither WebP nor image-set()). */
export function frameBackgroundImage(
  template: FrameTemplate,
  colorKey: string,
): string {
  const png = frameAssetPath(template, colorKey);
  return `image-set(url("${webpVariant(png)}") type("image/webp"), url("${png}") type("image/png"))`;
}

export function FrameLayer({
  template = DEFAULT_FRAME_TEMPLATE,
  colorIdentity,
  className,
  zIndex,
}: {
  template?: FrameTemplate;
  colorIdentity: ColorIdentity[] | undefined;
  className?: string;
  /** Optional inline z-index override. Templates that render a separate
   *  art layer beneath the frame (cut-out slot) pass a positive value so
   *  the frame sits on top of the art. Defaults to the base z-0 layer. */
  zIndex?: number;
}) {
  const colorKey = pickFrameColorKey(colorIdentity);
  return (
    <div
      aria-hidden
      className={cn(
        "pointer-events-none absolute inset-0",
        zIndex === undefined ? "z-0" : "",
        className,
      )}
      style={{
        backgroundImage: frameBackgroundImage(template, colorKey),
        backgroundSize: "100% 100%",
        backgroundRepeat: "no-repeat",
        ...(zIndex === undefined ? {} : { zIndex }),
      }}
    />
  );
}
