import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { FRAME_COLOR_KEYS, frameComboKey } from "@/lib/cards/frame-reference-registry";
import {
  CARD_KIND_VALUES,
  framesForKind,
  templateRefusesKind,
  templateSupportsKind,
} from "@/lib/creator/card-kinds";
import { FRAME_TEMPLATE_VALUES } from "@/types/card";
import { kindsByTemplate } from "@/tests/visual/matrix";

// ---------------------------------------------------------------------------
// The kind gate's baseline (TODO 4.5.0, proof 2): what every template refuses
// (templateRefusesKind — the server's kind gate, reference pinning, the
// walkthrough), what every kind's gallery offers (framesForKind with every
// combo published and with none), templateSupportsKind, and the kinds the
// visual matrix bakes per template (kindsByTemplate) — generated at the base
// of 4.5.0, when the gate was the hand-kept SHOWCASE_KIND_RESTRICTION table.
// 4.5.0 derives the same answers from the profiles' anatomy (kind-anatomy.ts)
// plus the trade-dress table (TREATMENT_KINDS); this pins them identical.
//
// A PR that MEANS to change what a frame dresses (a new template, a kind the
// owner lets a frame take) regenerates the fixture and says why:
//
//   UPDATE_KIND_GATE_FIXTURE=1 npx vitest run tests/unit/creator/kind-gate-baseline.test.ts
// ---------------------------------------------------------------------------

const FIXTURE = join(process.cwd(), "tests/unit/creator/fixtures/kind-gate-base.json");

const EVERY_COMBO: ReadonlySet<string> = new Set(
  FRAME_TEMPLATE_VALUES.flatMap((t) => FRAME_COLOR_KEYS.map((k) => frameComboKey(t, k))),
);
const NO_COMBO: ReadonlySet<string> = new Set();

type GateSnapshot = {
  refuses: Record<string, string[]>;
  supports: Record<string, string[]>;
  framesForKind: Record<string, { template: string; era: string; group: string; availableColorKeys: string[] }[]>;
  framesForKindUnpublished: Record<string, { template: string; era: string; group: string; availableColorKeys: string[] }[]>;
  matrixKinds: Record<string, string[]>;
};

function snapshot(): GateSnapshot {
  const refuses: Record<string, string[]> = {};
  const supports: Record<string, string[]> = {};
  for (const template of FRAME_TEMPLATE_VALUES) {
    refuses[template] = CARD_KIND_VALUES.filter((kind) => templateRefusesKind(template, kind));
    supports[template] = CARD_KIND_VALUES.filter((kind) => templateSupportsKind(template, kind));
  }
  const gallery = (verified: ReadonlySet<string>) =>
    Object.fromEntries(
      CARD_KIND_VALUES.map((kind) => [
        kind,
        framesForKind(kind, verified).map((f) => ({
          template: f.template,
          era: f.era,
          group: f.group,
          availableColorKeys: [...f.availableColorKeys],
        })),
      ]),
    );
  return {
    refuses,
    supports,
    framesForKind: gallery(EVERY_COMBO),
    framesForKindUnpublished: gallery(NO_COMBO),
    matrixKinds: Object.fromEntries([...kindsByTemplate()].map(([t, kinds]) => [t, [...kinds]])),
  };
}

if (process.env.UPDATE_KIND_GATE_FIXTURE === "1") {
  const base = execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim();
  writeFileSync(
    FIXTURE,
    `${JSON.stringify(
      {
        comment:
          "Generated by tests/unit/creator/kind-gate-baseline.test.ts (UPDATE_KIND_GATE_FIXTURE=1): every templateRefusesKind / templateSupportsKind pair, every framesForKind list and the visual matrix's kinds per template (TODO 4.5.0).",
        base,
        ...snapshot(),
      },
      null,
      1,
    )}\n`,
  );
}

describe("the kind gate against its 4.5.0 base (proof 2)", () => {
  const fixture = existsSync(FIXTURE) ? (JSON.parse(readFileSync(FIXTURE, "utf8")) as GateSnapshot & { base: string }) : null;
  const now = snapshot();

  it("has a fixture", () => {
    expect(fixture, `missing ${FIXTURE}`).not.toBeNull();
  });

  it("refuses exactly the same kinds on every template (templateRefusesKind)", () => {
    expect(now.refuses).toEqual(fixture!.refuses);
  });

  it("supports exactly the same kinds on every template (templateSupportsKind)", () => {
    expect(now.supports).toEqual(fixture!.supports);
  });

  it("offers exactly the same gallery for every kind, published or not (framesForKind)", () => {
    expect(now.framesForKind).toEqual(fixture!.framesForKind);
    expect(now.framesForKindUnpublished).toEqual(fixture!.framesForKindUnpublished);
  });

  it("hands the visual matrix the same kinds per template (kindsByTemplate)", () => {
    expect(now.matrixKinds).toEqual(fixture!.matrixKinds);
  });
});
