// GENERATED by scripts/generate-collector-metrics.mjs from the committed
// fonts — do not edit by hand (tests/unit/cards/collector-metrics.test.ts
// fails when it drifts from them: regenerate after rebuilding the collector
// face with `node scripts/generate-collector-metrics.mjs`).
//
// The collector line's metrics (TODO 4.9b): the advance of every glyph of
// the subset collector face (public/fonts/Montserrat-Medium.ttf — no
// kerning, so a run's width is the sum of its advances in the browser and
// in Satori alike) and the hhea line metrics of the three faces a collector
// run is set in. lib/cards/collector-layout.ts places every run by its
// BASELINE from these; both renderers draw at the computed x and top.
// Client-safe (no fs).

/** Font units per em of the collector face. */
export const COLLECTOR_UNITS_PER_EM = 1000;

/** Code point → advance in font units, for every glyph of the subset. */
export const COLLECTOR_ADVANCES: Readonly<Record<string, number>> = {
  " ": 269, "-": 383, "/": 352, 0: 667, 1: 370, 2: 574, 3: 572, 4: 669,
  5: 574, 6: 617, 7: 598, 8: 644, 9: 617, A: 732, B: 757, C: 713,
  D: 826, E: 670, F: 635, G: 772, H: 812, I: 310, J: 513, K: 719,
  L: 594, M: 955, N: 812, O: 840, P: 722, Q: 840, R: 727, S: 621,
  T: 587, U: 791, V: 712, W: 1126, X: 673, Y: 647, Z: 657, a: 598,
  b: 682, c: 571, d: 682, e: 612, f: 353, g: 690, h: 681, i: 279,
  j: 284, k: 615, l: 279, m: 1057, n: 681, o: 635, p: 682, q: 682,
  r: 410, s: 501, t: 414, u: 677, v: 559, w: 899, x: 552, y: 559,
  z: 521, "†": 560, "•": 314,
};

/** The bullet's ink box in font units (its vertical centre is the dot the
 *  ★ run is centred on). */
export const COLLECTOR_BULLET_BOX = { minX: 66, minY: 184, maxX: 247, maxY: 367 } as const;

export type LineMetrics = {
  unitsPerEm: number;
  /** hhea ascent / descent / lineGap, in em. A run set with
   *  `lineHeight: ascent + descent` puts its baseline exactly `ascent` em
   *  below its top in the browser and in Satori (lib/cards/rules-metrics.ts
   *  MPLANTIN_LINE_METRICS says the same of MPlantin). */
  ascent: number;
  descent: number;
  lineGap: number;
  capHeight: number;
  xHeight: number;
};

/** The three faces a collector run is set in: the collector face, the
 *  display face (Beleren Bold: the artist's small caps and the brand mark)
 *  and the body face (MPlantin: a clean download's footer text). */
export const COLLECTOR_FACES: Readonly<Record<"collector" | "display" | "body", LineMetrics>> = {
  collector: { unitsPerEm: 1000, ascent: 0.968, descent: 0.251, lineGap: 0, capHeight: 0.7, xHeight: 0.53 },
  display: { unitsPerEm: 2048, ascent: 0.936, descent: 0.2695, lineGap: 0, capHeight: 0.7002, xHeight: 0.5 },
  body: { unitsPerEm: 1000, ascent: 0.774, descent: 0.225, lineGap: 0.15, capHeight: 0, xHeight: 0 },
};
