// ---------------------------------------------------------------------------
// The collector line's font metrics (TODO 4.9b). Shared by
// scripts/generate-collector-metrics.mjs (writes lib/cards/collector-metrics.ts)
// and the unit test that keeps the generated table in step with the
// committed fonts (tests/unit/cards/collector-metrics.test.ts).
//
// Both renderers lay the collector line out from these numbers alone — the
// advance of every glyph of the subset face (public/fonts/Montserrat-Medium
// .ttf, no kerning: the subset dropped GPOS), and the hhea line metrics of
// the three faces a run can be set in (the collector face, Beleren Bold for
// the artist's synthesized small caps and the brand mark, MPlantin for a
// clean download's footer text) — so a run placed by its BASELINE lands on
// the same pixel row in the browser and in Satori (lib/cards/
// collector-layout.ts).
// ---------------------------------------------------------------------------

import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

const require = createRequire(import.meta.url);
const fontkit = require("@pdf-lib/fontkit");

/** The glyph set of the collector face (scripts/build-collector-font.mjs
 *  subsets to it): A–Z, a–z, 0–9, the slash, the hyphen, the bullet, the
 *  dagger and the space — 67 code points, every one in MPlantin's cmap. */
export const COLLECTOR_TEXT = " -/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz•†";

export const COLLECTOR_FONT_FILES = {
  collector: "public/fonts/Montserrat-Medium.ttf",
  display: "public/fonts/Beleren-Bold.ttf",
  body: "node_modules/mana-font/fonts/mplantin.ttf",
};

/** hhea ascent / descent / lineGap and the cap and x heights, in em. */
function lineMetrics(font) {
  const upm = font.unitsPerEm;
  const os2 = font["OS/2"];
  return {
    unitsPerEm: upm,
    ascent: font.ascent / upm,
    descent: Math.abs(font.descent) / upm,
    lineGap: font.lineGap / upm,
    capHeight: (os2?.capHeight || font.capHeight || 0) / upm,
    xHeight: (os2?.xHeight || font.xHeight || 0) / upm,
  };
}

/**
 * The table: the collector face's advance per code point (font units), its
 * ink box for the characters whose vertical extent the layout draws against
 * (the bullet, which is centred on the line's lower-case band), and the
 * three faces' line metrics.
 */
export function computeCollectorMetrics(root) {
  const at = (file) => path.join(root, file);
  const collector = fontkit.create(readFileSync(at(COLLECTOR_FONT_FILES.collector)));
  const display = fontkit.create(readFileSync(at(COLLECTOR_FONT_FILES.display)));
  const body = fontkit.create(readFileSync(at(COLLECTOR_FONT_FILES.body)));
  const advances = [];
  const codePoints = [...collector.characterSet].sort((a, b) => a - b);
  for (const cp of codePoints) {
    const glyph = collector.glyphForCodePoint(cp);
    if (!glyph || glyph.id === 0) continue;
    advances.push([cp, glyph.advanceWidth]);
  }
  const bullet = collector.glyphForCodePoint(0x2022);
  const bbox = bullet.bbox;
  return {
    unitsPerEm: collector.unitsPerEm,
    advances,
    bullet: { minY: bbox.minY, maxY: bbox.maxY, minX: bbox.minX, maxX: bbox.maxX },
    faces: {
      collector: lineMetrics(collector),
      display: lineMetrics(display),
      body: lineMetrics(body),
    },
  };
}

const fmt = (n) => (Number.isInteger(n) ? String(n) : n.toFixed(4).replace(/0+$/, "").replace(/\.$/, ""));
const key = (cp) => {
  const ch = String.fromCodePoint(cp);
  return /^[A-Za-z0-9]$/.test(ch) ? ch : JSON.stringify(ch);
};

function packed(items, perLine) {
  const lines = [];
  for (let i = 0; i < items.length; i += perLine) lines.push(`  ${items.slice(i, i + perLine).join(", ")},`);
  return lines.join("\n");
}

function face(m) {
  return `{ unitsPerEm: ${m.unitsPerEm}, ascent: ${fmt(m.ascent)}, descent: ${fmt(m.descent)}, lineGap: ${fmt(m.lineGap)}, capHeight: ${fmt(m.capHeight)}, xHeight: ${fmt(m.xHeight)} }`;
}

/** Source of lib/cards/collector-metrics.ts. */
export function renderCollectorMetricsModule({ unitsPerEm, advances, bullet, faces }) {
  return `// GENERATED by scripts/generate-collector-metrics.mjs from the committed
// fonts — do not edit by hand (tests/unit/cards/collector-metrics.test.ts
// fails when it drifts from them: regenerate after rebuilding the collector
// face with \`node scripts/generate-collector-metrics.mjs\`).
//
// The collector line's metrics (TODO 4.9b): the advance of every glyph of
// the subset collector face (public/fonts/Montserrat-Medium.ttf — no
// kerning, so a run's width is the sum of its advances in the browser and
// in Satori alike) and the hhea line metrics of the three faces a collector
// run is set in. lib/cards/collector-layout.ts places every run by its
// BASELINE from these; both renderers draw at the computed x and top.
// Client-safe (no fs).

/** Font units per em of the collector face. */
export const COLLECTOR_UNITS_PER_EM = ${unitsPerEm};

/** Code point → advance in font units, for every glyph of the subset. */
export const COLLECTOR_ADVANCES: Readonly<Record<string, number>> = {
${packed(
  advances.map(([cp, adv]) => `${key(cp)}: ${adv}`),
  8,
)}
};

/** The bullet's ink box in font units (its vertical centre is the dot the
 *  ★ run is centred on). */
export const COLLECTOR_BULLET_BOX = { minX: ${bullet.minX}, minY: ${bullet.minY}, maxX: ${bullet.maxX}, maxY: ${bullet.maxY} } as const;

export type LineMetrics = {
  unitsPerEm: number;
  /** hhea ascent / descent / lineGap, in em. A run set with
   *  \`lineHeight: ascent + descent\` puts its baseline exactly \`ascent\` em
   *  below its top in the browser and in Satori (lib/cards/rules-metrics.ts
   *  MPLANTIN_LINE_METRICS says the same of MPlantin). */
  ascent: number;
  descent: number;
  lineGap: number;
  capHeight: number;
  xHeight: number;
};

/** The three faces a collector run is set in: the collector face, the
 *  display face (Beleren Bold: the artist's small caps and the brand mark)
 *  and the body face (MPlantin: a clean download's footer text). */
export const COLLECTOR_FACES: Readonly<Record<"collector" | "display" | "body", LineMetrics>> = {
  collector: ${face(faces.collector)},
  display: ${face(faces.display)},
  body: ${face(faces.body)},
};
`;
}
